export enum QUERY_KEYS {
  'EQUIPMENTS' = 'EQUIPMENTS',
  'EQUIPMENT_MODELS' = 'EQUIPMENT_MODELS',
  'EQUIPMENT_STATES' = 'EQUIPMENT_STATES',
  'EQUIPMENT_LAST_STATES' = 'EQUIPMENT_LAST_STATES',
  'EQUIPMENTS_WITH_LAST_STATE' = 'EQUIPMENTS_WITH_LAST_STATE',
  'EQUIPMENT_POSITION_HISTORY' = 'EQUIPMENT_POSITION_HISTORY'
}
