export enum QUERY_KEYS {
  'EQUIPMENTS' = 'EQUIPMENTS',
  'EQUIPMENT_MODELS' = 'EQUIPMENT_MODELS',
  'EQUIPMENT_STATES' = 'EQUIPMENT_STATES',
  'EQUIPMENT_LAST_STATES' = 'EQUIPMENT_LAST_STATES',
  'EQUIPMENTS_WITH_LAST_STATE' = 'EQUIPMENTS_WITH_LAST_STATE',
  'EQUIPMENTS_LAST_POSITION' = 'EQUIPMENTS_LAST_POSITION',
  'EQUIPMENT_LAST_POSITIONS' = 'EQUIPMENT_LAST_POSITIONS'
}
