export enum QUERY_KEYS {
  'EQUIPMENT' = 'EQUIPMENT',
  'EQUIPMENT_MODELS' = 'EQUIPMENT_MODELS',
  'EQUIPMENT_STATE' = 'EQUIPMENT_STATE',
  'EQUIPMENT_STATE_HISTORY' = 'EQUIPMENT_STATE_HISTORY',
  'EQUIPMENT_POSITION_HISTORY' = 'EQUIPMENT_POSITION_HISTORY'
}
