// actionTypes.ts
export const FETCH_EQUIPMENT_STATES = 'FETCH_EQUIPMENT_STATES';
export const FETCH_MODELS = 'FETCH_MODELS';
export const FETCH_STATES = 'FETCH_STATES';

export const FETCH_EQUIPMENT_STATES_SUCCESS = 'FETCH_EQUIPMENT_STATES_SUCCESS';
export const FETCH_MODELS_SUCCESS = 'FETCH_MODELS_SUCCESS';
export const FETCH_STATES_SUCCESS = 'FETCH_STATES_SUCCESS';

export const FETCH_FAILURE = 'FETCH_FAILURE';
